[build]
  publish = "."
  command = "echo \"Static deploy\""

[[headers]]
  for = "/firebase.runtime-config.json"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

